In [8]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd

In [121]:
# load data
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(url, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
#print(dataframe.ix[:3])
#print(X.shape)

[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1.

In [8]:
# feature extraction
model = LogisticRegression()
rfe = RFE(model, 3)
fit = rfe.fit(X, Y)
print("Num Features: %d") % fit.n_features_
print("Selected Features: %s") % fit.support_
print("Feature Ranking: %s") % fit.ranking_

Num Features: 3
Selected Features: [ True False False False False  True  True False]
Feature Ranking: [1 2 3 5 6 1 1 4]


In [22]:
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

In [17]:
iris = datasets.load_iris()
X, y = iris.data, iris.target
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [20]:
c = OneVsRestClassifier(LinearSVC(random_state=0))
c.fit(X, y).predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
model = SelectFromModel(c, prefit=True)
X_new = model.transform(X)
print(X_new[1:6,:])
print(X[1:6,:])

[[1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]]
[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]


In [126]:
#train_data = np.loadtxt("/Users/jain/Desktop/coding.all.countWOH9Samples.log2tpm.txt", delimiter="\t", unpack=False)
#train_label = np.loadtxt("/Users/jain/Desktop/all.count.data.namesWOH9Samples.features", delimiter="\t", unpack=False)

df1 = read_csv("/Users/jain/Desktop/coding.all.countWOH9Samples.log2tpm.txt",index_col=0,sep="\t")
df2 = read_csv("/Users/jain/Desktop/all.count.data.namesWOH9Samples.features", index_col=0,sep="\t")

variance = df1.var(axis=1)
topQ = df1[variance >= variance.quantile(0.75)]
geneNames = topQ.index

train_data = topQ.values
train_data = train_data.transpose()
train_label = df2.values

###Labels of control and preeclampsia samples based on oxygen samples
labels = train_label[:,4]
#labels = labels.astype(float)

In [131]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
#model = RandomForestClassifier()
#rfe = RFE(estimator=model,step=5)
#fit = rfe.fit(train_data, labels)
#print(labels.shape)
#print(train_data.shape)
model = ExtraTreesClassifier(n_estimators=1000)
model.fit(train_data, labels)
im = model.feature_importances_
selectedGenes = topQ[im > 0.001]
print(im[im > 0.001])
print(selectedGenes.index)
selectedGenes.to_csv("/Users/jain/Desktop/selectedGenesRandomForest.txt", sep='\t')
#print("Num Features: %d") % fit.n_features_
#print("Selected Features: %s") % fit.support_
#print("Feature Ranking: %s") % fit.ranking_


[0.00106723 0.00121341 0.00327608 0.00239641 0.00154525 0.00150893
 0.00247891 0.00215961 0.00102826 0.00103791 0.00119756 0.00102966
 0.00117413 0.00251578 0.00184719 0.00177126 0.00102393 0.00475787
 0.00196515 0.00217787 0.00104418 0.00115838 0.00180267 0.00208137
 0.00126194 0.00120737 0.00254844 0.00212037 0.00119062 0.00166626
 0.00122023 0.00109196 0.00135983 0.00286288 0.00145776 0.00229431
 0.00111075 0.00141154 0.00100302 0.00111619 0.00113077 0.00158072
 0.00108258 0.0010729  0.00124831 0.0011691  0.00206474 0.00170496
 0.00177025 0.00161942 0.00130059 0.0019953  0.00136411 0.00109581
 0.00245278 0.00178082 0.00115983 0.00144249 0.0016284  0.00196747
 0.00154583 0.00111172 0.00100975 0.00174677 0.00106358 0.00113842
 0.00101486 0.00108867 0.00156285 0.00116474 0.00102559 0.00122656
 0.00154481 0.00106703 0.00149098 0.00135882 0.00109392 0.00322992
 0.00136906 0.00167309 0.0012414  0.00126951 0.00151507 0.00150411
 0.001431   0.00131121 0.00175744 0.00108389 0.00164015 0.0014